if(TARGET AgfaceOpenCV::OpenCV)
    set(OpenCV_FOUND TRUE)
    return()
endif()

set(_AGFACE_OPENCV_SOURCE_CANDIDATES
    "${CMAKE_SOURCE_DIR}/third_party/opencv"
    "${AGFACE_OPENCV_SOURCE_DIR}"
    "$ENV{AGFACE_OPENCV_SOURCE_DIR}"
)

set(_AGFACE_OPENCV_SOURCE_DIR_RESOLVED "")
foreach(_candidate IN LISTS _AGFACE_OPENCV_SOURCE_CANDIDATES)
    if(_candidate AND EXISTS "${_candidate}/CMakeLists.txt")
        set(_AGFACE_OPENCV_SOURCE_DIR_RESOLVED "${_candidate}")
        break()
    endif()
endforeach()

if(_AGFACE_OPENCV_SOURCE_DIR_RESOLVED)
    if(NOT TARGET opencv_core)
        set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
        set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
        set(BUILD_PERF_TESTS OFF CACHE BOOL "" FORCE)
        set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        set(BUILD_DOCS OFF CACHE BOOL "" FORCE)
        set(BUILD_PACKAGE OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_apps OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_java OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_python OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_ts OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_world OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_nonfree OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_contrib OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_video OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_videostab OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_calib3d OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_features2d OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_flann OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_gpu OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_ml OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_objdetect OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_photo OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_stitching OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_superres OFF CACHE BOOL "" FORCE)
        set(BUILD_opencv_ocl OFF CACHE BOOL "" FORCE)
        set(WITH_CUDA OFF CACHE BOOL "" FORCE)
        set(WITH_OPENCL OFF CACHE BOOL "" FORCE)
        set(WITH_OPENGL OFF CACHE BOOL "" FORCE)
        set(WITH_FFMPEG OFF CACHE BOOL "" FORCE)
        set(WITH_GTK OFF CACHE BOOL "" FORCE)
        set(WITH_QT OFF CACHE BOOL "" FORCE)
        set(WITH_VTK OFF CACHE BOOL "" FORCE)
        set(WITH_1394 OFF CACHE BOOL "" FORCE)
        set(WITH_V4L OFF CACHE BOOL "" FORCE)
        set(WITH_GSTREAMER OFF CACHE BOOL "" FORCE)
        set(WITH_TIFF OFF CACHE BOOL "" FORCE)
        set(WITH_JASPER OFF CACHE BOOL "" FORCE)
        set(WITH_OPENEXR OFF CACHE BOOL "" FORCE)
        set(WITH_IPP OFF CACHE BOOL "" FORCE)
        set(WITH_WEBP OFF CACHE BOOL "" FORCE)
        set(ENABLE_PRECOMPILED_HEADERS OFF CACHE BOOL "" FORCE)
        add_subdirectory("${_AGFACE_OPENCV_SOURCE_DIR_RESOLVED}" "${CMAKE_BINARY_DIR}/third_party/opencv" EXCLUDE_FROM_ALL)
    endif()

    set(OpenCV_INCLUDE_DIRS
        "${_AGFACE_OPENCV_SOURCE_DIR_RESOLVED}/include"
        "${_AGFACE_OPENCV_SOURCE_DIR_RESOLVED}/modules/core/include"
        "${_AGFACE_OPENCV_SOURCE_DIR_RESOLVED}/modules/imgproc/include"
        "${_AGFACE_OPENCV_SOURCE_DIR_RESOLVED}/modules/highgui/include"
        "${CMAKE_BINARY_DIR}/third_party/opencv"
    )
    set(OpenCV_LIBS opencv_core opencv_imgproc opencv_highgui)
    set(OpenCV_FOUND TRUE)
    set(AGFACE_OPENCV_LEGACY_SOURCE ON)
else()
    find_package(OpenCV QUIET COMPONENTS core imgproc imgcodecs)
    if(NOT OpenCV_FOUND)
        find_package(OpenCV QUIET COMPONENTS core imgproc highgui)
    endif()
endif()

if(OpenCV_FOUND AND NOT TARGET agface_opencv)
    add_library(agface_opencv INTERFACE)
    target_include_directories(agface_opencv INTERFACE ${OpenCV_INCLUDE_DIRS})
    target_link_libraries(agface_opencv INTERFACE ${OpenCV_LIBS})
    add_library(AgfaceOpenCV::OpenCV ALIAS agface_opencv)
endif()
